### ISSUE TITLE
Statistics screen

### ISSUE THREAD

**Issue by Nikoichu** [mimoguz/tripeaks-gdx#14]
It would be nice if the game tracked stuff like wins/losses, win percentage, average undos, chain length and cards taken from deck, as well as longest chain and games per day.

Perhaps the statistics screen could be accessed from a fourth button on the main menu or from the options screen.

**Comment by mimoguz** [comment]
Yes, general statistics is one of the items of the next update I'm planning. Played games, wins, minimum and average moves for each game type. This is too simple a game for detailed statistics though. 🙂

I will count a game lost if
* player made at least one move,
* a new game was started before clearing it.

**Comment by mimoguz** [comment]
So, I ended up with much simpler design than I've first intended: [Statistics dialog](https://github.com/mimoguz/tripeaks-gdx/blob/Stats/screenshots/statistics.png). 🤷

I will need new strings of course. I'll put them here instead of individual issues.

The menu item to display statistics dialog:
* Statistics

This is the title for the aggregated stats:
* All

The label for the total number of games played:
* Games:

The label for the number of wins:
* Wins:

The label for the number of cards in the longest sequence the player achieved:
* The longest chain:

Thanks!

**Comment by rellikmil** [comment]
Russian
Statistics - Статистика
All - Все игры
Games: - Игр:
Wins: - Побед:
The longest chain: - Длинная цепочка из:

**Comment by Nikoichu** [comment]
Bulgarian:
Statistics - Статистика
All - Всички
Games: - Игри:
Wins: - Победи:
The longest chain: - Най-дълга поредица:

**Comment by JVariance** [comment]
German:
Statistics - Statistiken
All - Alle
Games: - Spiele
Wins: - Siege
The longest chain: - Die längste Folge

**Comment by ghost** [comment]
Spanish:
Statistics - Estadísticas
All - Todo
Games: - Partidas:
Wins: - Victorias:
The longest chain: - La cadena más larga:

**Comment by ghost** [comment]
Portuguese:

Statistics - Estatísticas
All - Total
Games - Partidas:
Wins - Vitórias:
The longest chain - Sequência mais longa:

**Comment by mimoguz** [comment]
Sorry for the delay. All translations have been completed, and now I'm preparing a new release.

Thank you all.
