### ISSUE TITLE
Wrong card count on end screen

### ISSUE THREAD

**Issue by bergamote** [mimoguz/tripeaks-gdx#24]
I just finished a game having only used about half the cards in the stack, but the end screen told me I had used 35 cards. This is the first time it happened and I don't know how to reproduce this bug.

![Screenshot_2023-09-04-10-49-22-948_ogz tripeaks](https://github.com/mimoguz/tripeaks-gdx/assets/2508198/9aa9446c-ef16-4345-9f34-6184bee08339)

**Comment by mimoguz** [comment]
Yeah, there are some issues with stat-keeping logic in the current version. There is a current effort to re-write some parts of the game (which goes very slowly, due to some health problems). Hopefully that will address all currently open issues, including this one.

I'll still try to figure out what's going on here though.

**Comment by mimoguz** [comment]
As I will hopefully release the new version soon, I'm closing the old issues. Please feel free to re-open if the problem resurfaces after v1.1 update.
